INSERT INTO [dbo].[AspNetUsers]
           ([Id]
           ,[AccessFailedCount]
           ,[ConcurrencyStamp]
           ,[Email]
           ,[EmailConfirmed]
           ,[LockoutEnabled]
           ,[LockoutEnd]
           ,[NormalizedEmail]
           ,[NormalizedUserName]
           ,[PasswordHash]
           ,[PhoneNumber]
           ,[PhoneNumberConfirmed]
           ,[SecurityStamp]
           ,[TwoFactorEnabled]
           ,[UserName])
     VALUES
           (PlaceholderId
           ,PlaceholderAccessFailedCount
           ,PlaceholderConcurrencyStamp
           ,PlaceholderEmail
           ,PlaceholderEmailConfirmed
           ,PlaceholderLockoutEnabled
           ,PlaceholderLockoutEnd
           ,PlaceholderNormalizedEmail
           ,PlaceholderNormalizedUserName
           ,PlaceholderPasswordHash
           ,PlaceholderPhoneNumber
           ,PlaceholderPhoneNumberConfirmed
           ,PlaceholderSecurityStamp
           ,PlaceholderTwoFactorEnabled
           ,PlaceholderUserName)